### ISSUE TITLE
missing libssl and libcrypto

### ISSUE THREAD

**Issue by husseinharake** [eth-cscs/manta#6]
Dear Support, 

I am writing to report an issue I encountered after installing Manta on Castaneda system. The Manta binary raised an error related to missing libraries, specifically, libssl.so.1.1 and libcrypto.so.1.1.

Castaneda, which is based on Ubuntu, come with libssl3 as the default SSL library. However, the snap packaging system included the core18 package, which is the runtime environment for Ubuntu 18.04. This package contains the required missing libraries.

Here's the information from the ldd command for the Manta binary:

root@castaneda:~# ldd ./manta
	linux-vdso.so.1 (0x00007fff542a5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fc63921c000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc6391fc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc6391f7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc63910e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc639109000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc638ee1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc639dd2000

To resolve the issue, I created the necessary symbolic links, which provided a workaround. However, I believe this is not an ideal solution. It may be worth considering updating Manta to use the newer version of libssl and libcrypto to ensure compatibility.

Here are the commands I used to create the symbolic links:

ln -s /snap/core18/2751/usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
ln -s /snap/core18/2751/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1

Thanks for your support and best regards
Hussein

**Comment by Masber** [comment]
Dear @husseinharake ,

thank you for your feedback, we will take note of this
