### ISSUE TITLE
[Feature] Create example configuration 

### ISSUE THREAD

**Issue by alexlovelltroy** [eth-cscs/manta#85]
Manta's source code includes an example configuration file.  It would be nice to have a command to generate one for users that don't have a current checkout of the code.

Bonus points if it asks the user for input as part of generating the config.

**Comment by Masber** [comment]
Manta starts and looks for the configuration file.
If configuration file could not be found and manta is run interactively (not in a CICD pipeline or not withing a script) it will as prompt the user for the parameters to create a configuration file:

- site name*
- base_url*
- socks5_proxy
- k8s api url*
- local vault url*
- local vault secret path*
- local vault role id*
- path to CA cert*

**Comment by Masber** [comment]
this is done in version 1.46.0
