### ISSUE TITLE
BUG: allow using `help` command without the need for a cert

### ISSUE THREAD

**Issue by davidallendj** [eth-cscs/manta#87]
It is not currently possible to invoke `manta` without a valid CA public root file. Trying to do something like `manta help` (or any command) to view available commands/subcommands result in the following error:

```
ERROR - CA public root file 'path/to/cert.pem' not found. Exit
```

I'm not sure if this is by design, but it would be useful to be able to run `help` to see commands without needing this.

**Comment by Masber** [comment]
Hi, I believe, most recent release has fixed this.
I’m closing this ticket
