### ISSUE TITLE
BUG: building `manta` expects `mesa` to be local

### ISSUE THREAD

**Issue by davidallendj** [eth-cscs/manta#88]
Running the `scripts/build` script as described in the README fails due to the Cargo.toml including [the path to mesa in the dependencies list](https://github.com/eth-cscs/manta/blob/main/Cargo.toml#L20) instead of the mesa version commented out above. Having to manually change this may cause some friction when trying to build `manta` without knowledge of using rust/cargo.

**Comment by Masber** [comment]
Hi, 

local mesa is only for development purposes.
you can edit your cargo.toml like below
```
...
[dependencies]
mesa = "0.41.5"
# mesa = { path = "../mesa" } # Only for development purposes
...
```
And this will pull mesa from crates.io

**Comment by davidallendj** [comment]
Should pulling from crates.io not be the default? Also, I don't think there's anything in the README that points out needing to make this change.

**Comment by Masber** [comment]
Yes should be the default, we can update the README explaining this

Sent from my iPhone

On 25 Sep 2024, at 23:17, David Allen ***@***.***> wrote:

﻿

Should pulling from crates.io not be the default? Also, I don't think there's anything in the README that points out needing to make this change.

**Comment by Masber** [comment]
closing this, this issues has been addressed in the docs.
